app = "agentkit-app"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

[checks]
  [checks.primary]
    port = 8080
    type = "http"
    interval = "30s"
    timeout = "10s"
    grace_period = "30s"

[experimental]
  auto_rollback = true
